import random
websites = {
    'VKontakte': 'https://vk.com/',
    'Yandex': 'https://yandex.ru/profile/',
    'Yandex.Taxi': 'https://taxi.yandex.ru/profile/',
    'Kinopoisk': 'https://www.kinopoisk.ru/user/',
    'Gazeta.ru': 'https://www.gazeta.ru/user//',
    'Rambler': 'https://id.rambler.ru/users/',
    'GitHub': 'https://github.com/',
    'Telegram': 'https://t.me/',
    'YouTube': 'https://www.youtube.com/',
    'TikTok': 'https://www.tiktok.com/@',
    'Snapchat': 'https://www.snapchat.com/add/',
    'Twitch': 'https://www.twitch.tv/',
    'Amazon': 'https://www.amazon.com/gp/profile/amzn1.account.',
    'Wikipedia': 'https://en.wikipedia.org/wiki/User:',
    'Stack Overflow': 'https://stackoverflow.com/users/',
    'Dribbble': 'https://dribbble.com/',
    'Behance': 'https://www.behance.net/',
    'DeviantArt': 'https://www.deviantart.com/',
}
websites_keys = [
    'VKontakte',
    'Yandex',
    'Yandex.Taxi',
    'Kinopoisk',
    'Gazeta.ru',
    'Rambler',
    'GitHub',
    'Telegram',
    'YouTube',
    'TikTok',
    'Snapchat',
    'Twitch',
    'Amazon',
    'Wikipedia',
    'Stack Overflow',
    'Dribbble',
    'Behance',
    'DeviantArt',
]
user_agent_list = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1',
    'Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363',
]

headers={"User-Agent": user_agent_list[random.randint(0, len(user_agent_list)-1)]}